import {
  RegExpMatcher,
  pattern,
  collapseDuplicatesTransformer,
  resolveConfusablesTransformer,
  resolveLeetSpeakTransformer,
  skipNonAlphabeticTransformer,
  toAsciiLowerCaseTransformer,
} from "obscenity";

const SLUR_PATTERNS = [
  { id: 1, pattern: pattern`battyboy` },
  { id: 2, pattern: pattern`beaner` },
  { id: 3, pattern: pattern`bulldyke` },
  { id: 4, pattern: pattern`carpetmuncher` },
  { id: 5, pattern: pattern`chingchong` },
  { id: 6, pattern: pattern`chink` },
  { id: 7, pattern: pattern`coolie` },
  { id: 8, pattern: pattern`cripple` },
  { id: 9, pattern: pattern`currymuncher` },
  { id: 10, pattern: pattern`darkie` },
  { id: 11, pattern: pattern`darky` },
  { id: 12, pattern: pattern`dothead` },
  { id: 13, pattern: pattern`dyke` },
  { id: 14, pattern: pattern`faggot` },
  { id: 15, pattern: pattern`gash` },
  { id: 16, pattern: pattern`gook` },
  { id: 17, pattern: pattern`groid` },
  { id: 18, pattern: pattern`gypsy` },
  { id: 19, pattern: pattern`harlot` },
  { id: 20, pattern: pattern`heeb` },
  { id: 21, pattern: pattern`heshe` },
  { id: 22, pattern: pattern`hoe` },
  { id: 23, pattern: pattern`hymie` },
  { id: 24, pattern: pattern`injun` },
  { id: 25, pattern: pattern`jewboy` },
  { id: 26, pattern: pattern`jigaboo` },
  { id: 27, pattern: pattern`junglebunny` },
  { id: 28, pattern: pattern`kike` },
  { id: 29, pattern: pattern`ladyboy` },
  { id: 30, pattern: pattern`libtard` },
  { id: 31, pattern: pattern`midget` },
  { id: 32, pattern: pattern`mongoloid` },
  { id: 33, pattern: pattern`mooslim` },
  { id: 34, pattern: pattern`mulignan` },
  { id: 35, pattern: pattern`negro` },
  { id: 36, pattern: pattern`nigga` },
  { id: 37, pattern: pattern`nigger` },
  { id: 38, pattern: pattern`niglet` },
  { id: 39, pattern: pattern`nigr` },
  { id: 40, pattern: pattern`paki` },
  { id: 41, pattern: pattern`pickaninny` },
  { id: 42, pattern: pattern`poof` },
  { id: 43, pattern: pattern`poofter` },
  { id: 44, pattern: pattern`porchmonkey` },
  { id: 45, pattern: pattern`raghead` },
  { id: 46, pattern: pattern`redskin` },
  { id: 47, pattern: pattern`retard` },
  { id: 48, pattern: pattern`retarded` },
  { id: 49, pattern: pattern`rugmuncher` },
  { id: 50, pattern: pattern`sandnigger` },
  { id: 51, pattern: pattern`shemale` },
  { id: 52, pattern: pattern`shylock` },
  { id: 53, pattern: pattern`skank` },
  { id: 54, pattern: pattern`slanteye` },
  { id: 55, pattern: pattern`slut` },
  { id: 56, pattern: pattern`spastic` },
  { id: 57, pattern: pattern`tarbaby` },
  { id: 58, pattern: pattern`thot` },
  { id: 59, pattern: pattern`towelhead` },
  { id: 60, pattern: pattern`tranny` },
  { id: 61, pattern: pattern`twat` },
  { id: 62, pattern: pattern`wetback` },
  { id: 63, pattern: pattern`whore` },
  { id: 64, pattern: pattern`zionazi` },
  { id: 65, pattern: pattern`zipperhead` },
];

const matcher = new RegExpMatcher({
  blacklistedTerms: SLUR_PATTERNS,
  blacklistMatcherTransformers: [
    resolveConfusablesTransformer(),
    resolveLeetSpeakTransformer(),
    toAsciiLowerCaseTransformer(),
    skipNonAlphabeticTransformer(),
    collapseDuplicatesTransformer(),
  ],
});

export function containsSlur(text) {
  if (!text) return false;
  return matcher.hasMatch(text);
}
